import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Bowlby_One_SC, DM_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { SVGFilters } from "@/components/SVGFilter";

const bowlby = Bowlby_One_SC({
  variable: "--font-bowlby-sc",
  display: "swap",
  subsets: ["latin"],
  weight: "400",
});

const dmMono = DM_Mono({
  variable: "--font-dm-mono",
  display: "swap",
  subsets: ["latin"],
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${bowlby.variable} ${dmMono.variable} h-full antialiased font-mono font-medium text-zinc-800`}
    >
      <body
        className={`${bowlby.variable} ${dmMono.variable} h-full antialiased font-mono font-medium text-zinc-800`}
      >
        <main>
          <Header />
          {children}
        </main>
        <SVGFilters/>
      </body>
    </html>
  );
}
